# Copies and viewing :


In [8]:
import numpy as np
a = np.array([1,2,3,4]) # one dimension array

In [10]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [13]:
print(np.shares_memory(a,b))

True


In [17]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [31]:
a = np.arange(10)
b = a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [29]:
print(np.shares_memory(a,b))

False


# Random number Generator:

In [50]:
a = np.random.randint(0,20,20)
print(a)

[14 12  7 10  5 16 11 16  2 16 10  3  6  2 10  4 13 13  9 18]


In [52]:
mask=(a%2==0)

In [54]:
mask_a = a[mask]
print(mask_a)

[14 12 10 16 16  2 16 10  6  2 10  4 18]


In [56]:
a[mask] = -1
print(a)

[-1 -1  7 -1  5 -1 11 -1 -1 -1 -1  3 -1 -1 -1 -1 13 13  9 -1]


# Element Wise Operations :

## 1. Basic Operation 

In [61]:
a = np.array([1,2,3,4])
print(a+1) #add + 1

[2 3 4 5]


In [63]:
print(a**2) #squares

[ 1  4  9 16]


## 2. All Arthimetic operators Element Wise :

In [66]:
b = np.ones(4) + 1     #[2 2 2 2]
print("a = ",a)
print("b = ",b)

a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [68]:
print(a*b)

[2. 4. 6. 8.]


In [70]:
print(a-b)

[-1.  0.  1.  2.]


In [72]:
# matrix Multiplication
c = np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [78]:
print(c*c)
print("***************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## 3. Comparision Operators :

In [87]:
a = np.array([1,2,3,4])
b = np.array([5,2,7,4])
print(a==b)

[False  True False  True]


In [89]:
print(a>b)

[False False False False]


In [98]:
print(a<b)

[ True  True  True  True]


In [93]:
# Array wise comparison
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [95]:
print(np.array_equal(a,c))

True


## 4. Logical Operators:

In [108]:
a = np.array([1,0,1,0],dtype = "bool")
b = np.array([1,1,0,0],dtype = "bool")

In [110]:
print(np.logical_or(a,b))

[ True  True  True False]


In [112]:
print(np.logical_and(a,b))

[ True False False False]


## Trigonometry/Transcendental Functions

In [115]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [117]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [119]:
print(np.cos(a))

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [121]:
print(np.tan(a))

[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]


In [125]:
np.log(a)

C:\Users\rupes\AppData\Local\Temp\ipykernel_8960\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])