In [1]:
#writing to a csv file
import csv
with open("data.csv","w",newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["Karun","21","kakinada"])
    writer.writerow(["Mani","20","Kakinada"])

In [2]:
import csv
with open("data.csv",'r') as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['Karun', '21', 'kakinada']
['Mani', '20', 'Kakinada']


# Python Libraries:
Numpy:
-----
  Numpy stands for numerical python.
  It is a standard library.
  It is used for numerical computing with multi-dimensional arrays.
  It provides mathematical functions, linear algebra and random number generation.
  

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
l = range(1000)
%timeit [i**2 for i in l]

247 μs ± 10.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
a = np.arange(1000)
%timeit a**2

6.2 μs ± 469 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Creating Arrays:
----------------

In [9]:
a = np.array([1,2,3,4]) # one dimension array

In [10]:
print(a.ndim)

1


In [11]:
b = np.array([[1,2,3],[4,5,6]]) # two - dimensional array
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
print(b.ndim)

2


In [13]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [14]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
print(a.shape)

(4,)


In [16]:
print(b.shape)

(2, 3)


In [17]:
print(c.shape)

(2, 2, 2)


In [18]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


Functions for creating array:
---------------------------

In [20]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [22]:
# using Linspace
a = np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [23]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [24]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
a = np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [27]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [28]:
print(np.diag(a))

[1 2 3 4]


# Basic Data Types

In [30]:
a = np.arange(10)
print(a.dtype)

int32


In [31]:
a = np.arange(10,dtype="float")
print(a.dtype)

float64


In [32]:
a = np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other Datatype

In [34]:
a = np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [35]:
a = np.array([True,False])
print(a.dtype)

bool


In [36]:
a = np.array(['pavan','mani'])
print(a.dtype) #unicode string type

<U5


# Indexing and slicing

In [38]:
a = np.arange(10)
print(a[5])

5


In [39]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [40]:
a[2,1] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# Slicing : 

In [79]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
print(a[1:8:2])

[1 3 5 7]


In [83]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])